### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by loongmxbt** [PyPSA/linopy#1]
In `examples/create-a-model.ipynb`, when I run into
```
m.add_constraints(3*x + 7*y, '>=', 10)
m.add_constraints(5*x + 2*y, '>=', 3);
```
The console shows:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-72c2b3a3f44b> in <module>
----> 1 m.add_constraints(3*x + 7*y, '>=', 10)
      2 m.add_constraints(5*x + 2*y, '>=', 3);

TypeError: add_constraints() missing 1 required positional argument: 'rhs'
```

Python version 3.7.9
pip install linopy

**Comment by FabianHofmann** [comment]
hey @loongmxbt the code is aligned to the current master. But I will update the version today, so this should also work.

**Comment by loongmxbt** [comment]
Thanks @FabianHofmann, the example works fine now.
Another question, will this library replace linopt.py in PyPSA or be used in PyPSA in future?

**Comment by FabianHofmann** [comment]
you're welcome, yes this is very likely. But before we have to do some benchmarks
