### ISSUE TITLE
Shuffled constraints and variables causing infeasibilities

### ISSUE THREAD

**Issue by avautrin** [PyPSA/linopy#107]
Dear linopy team,

I am currently using linopy 0.1.4 with PyPSA 0.22.1

While trying to solve a small optimisation model via PyPSA, I encountered some infeasibilities on a model which shouldn't have any. The issue happens in the specific case where I combine unit commitment, ramp constraints and rolling horizon - the first iteration always goes well, and the second is found infeasible. 

I tried to dig into the PyPSA and linopy code and it seems like the constraints are well-written all along the way, except at the very end during the export to the lp file. In the LP file, right and left hand terms are mixed, grouping part of constraints that are not related, hence causing the infeasibilities.
When rolling horizon is disabled, it does not lead to infeasibilities but constraints are still not written properly...
However, the to_file linopy function is a bit beyond my capabilities, and it is likely I missed something upstream, too. 

Here is the code used for the tests, the logs, and the dataset. Thanks a lot for your help!

```
n = pypsa.Network()
    n.import_from_csv_folder("main/test")

    n_periods = 1000
    for i in range(n_periods):
        print("Iteration " + str(i+1) + " over " + str(n_periods))
        begin = i * int(len(n.snapshots) / n_periods)
        end = min((i + 1) * int(len(n.snapshots) / n_periods + 1) + 2, len(n.snapshots))

        m = n.optimize.create_model(snapshots=n.snapshots[begin: end], linearized_unit_commitment=False)

        m.to_file("pypsa.lp")
        n.optimize.solve_model(solver_name='gurobi')

        try:
            se = m.compute_set_of_infeasible_constraints()
            print(se)
        except:
            print("worked")
```
```
IIS runtime: 0.00 seconds (0.00 work units)
 c112: x8 <= 0

 c113: x1 <= 10000

 c118: x4 <= 10000

 c294: x0 <= 10000

 c295: x2 <= 5000

 c296: x3 <= 5000

 c297: x5 <= 7500
[test (1).zip](https://github.com/PyPSA/linopy/files/11145974/test.1.zip)


 c299: x6 <= 7500

 c298: x7 <= 7500

 c574: x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 = 200000
```

**Comment by avautrin** [comment]
Hi linopy team, did you have a chance to consider the following issue? It seems like it lies with the lp file writing, maybe because coordinates are missing, creating a shift between lhs and rhs. Your help/guidance on this would be highly appreciated! thanks a lot

**Comment by FabianHofmann** [comment]
Hey @avautrin. Sorry for the late reply, just came back from my vacations. No, I am pretty sure it has nothing to do with a shuffling of the constraints. If you run this 

```python 
for key in se:
    print(key)
    print(se[key].to_series()[lambda ds: ds != -1])
```

you see that the infeasible constraints are at one time step and are related to the ramp limit and the generator capacity limits. In case of an infeasibility, you can always introduce a load shedding as a first measure and see where the system suffers from energy shortage. 

Please reopen if you still encounter problems :)

**Comment by avautrin** [comment]
Hi @FabianHofmann, thanks for your answer - unfortunately I think the optimisation problem is feasible, and the issue lies in the constraint writing in lp :) My main insight is that switching to ",io_api='direct'" (with gurobi) solves the issue and makes it feasible. But all solvers do not have a direct api connection...

Also, a manual search and replace in the lp file (to have understandable names instead of "x1" etc - please point to a more convenient solution if any..) showed that lhs did not match rhs: e.g., two variables used in ramp of "Gas CCGT" appear in the same constraint as the ramp limit value of "Electricity sink", and the other way...

Thanks a lot for your support!

**Comment by FabianHofmann** [comment]
Could you have a look whether the changes in #113 fixes the issue

**Comment by avautrin** [comment]
It works perfectly @FabianHofmann, thanks **a lot**!

**Comment by FabianHofmann** [comment]
Great to hear! Thanks to you for being so patient and finding this bug!
