### ISSUE TITLE
Conditional sums in constraints

### ISSUE THREAD

**Issue by willu47** [PyPSA/linopy#108]
## Problem

I cannot work out how to implement a conditional sum using linopy and xarray syntax.  One key constraint in OSeMOSYS requires the cumulative sum of new capacity as shown in the GNU MathProg syntax below:

```ampl
s.t. CAa1_TotalNewCapacity{r in REGION, t in TECHNOLOGY, y in YEAR}:
	AccumulatedNewCapacity[r,t,y]
	=
	sum{yy in YEAR: y-yy < OperationalLife[r,t] && y - yy >= 0} NewCapacity[r,t,yy];
```
The Pyomo implementation of this constraint looks like this:

```python
def TotalNewCapacity_1_rule(model, r, t, y):
    return model.AccumulatedNewCapacity[r, t, y] == sum(
        model.NewCapacity[r, t, yy]
        for yy in model.YEAR
        if ((y - yy < model.OperationalLife[r, t]) and (y - yy >= 0))
    )
model.TotalNewCapacity_1 = Constraint(
    model.REGION, model.TECHNOLOGY, model.YEAR, rule=TotalNewCapacity_1_rule
)
```

And here's the mathematical formulation from the [2011 paper](https://doi.org/10.1016/j.enpol.2011.06.033):

$$
ANC_{rty} = \sum_{yy:  y-yy < OL_{rt} AND y-yy >= 0} NC_{rtyy}
\quad \forall r \in REGION, t \in TECHNOLOGY, y \in YEAR \\
$$

## Context

Hi! Many thanks for the great library.  I have been exploring [porting OSeMOSYS over to use Linopy](https://github.com/OSeMOSYS/OSeMOSYS_linopy), and am struggling with the xarray/linopy syntax for the more complicated constraints. If you could help me figure out the syntax, I'd be happy to contribute an example Jupyter Notebook for the documentation.

## Minimal working example

```python
import xarray as xy
from linopy import Model
import numpy as np

data_vars = {
'OperationalLife': xy.DataArray(data=np.array([[2.0]]), dims=['REGION', 'TECHNOLOGY'], 
                                coords={'REGION': ['SIMPLICITY'], 'TECHNOLOGY': ['TD2']}, 
                                name='OperationalLife')
}
coords = {
'REGION': ['SIMPLICITY'],
'TECHNOLOGY': ['TD2'],
'YEAR': [2010, 2011, 2012, 2013]
}

# Dataset containing all the parameters read in from an OSeMOSYS file
ds = xy.Dataset(data_vars=data_vars, coords=coords)

m = Model(force_dim_names=True)

RTeY = [ds.coords['REGION'], ds.coords['TECHNOLOGY'], ds.coords['YEAR']]
accumulated_new_capacity = m.add_variables(lower=0, upper=np.inf, coords=RTeY, name='AccumulatedNewCapacity', integer=False)
new_capacity = m.add_variables(lower=0, upper=np.inf, coords=RTeY, name='NewCapacity', integer=False)
```

**Comment by willu47** [comment]
I believe the following gives me the correct answer, but it's a little messy.

```python
def bounds(model, r, t, y):
    return accumulated_new_capacity[r,t,y] - 1 * \
                sum(new_capacity[r,t,yy] for yy in ds.coords['YEAR'].values 
                    if (y-yy >= 0) and (y-yy <= ds['OperationalLife'].sel({'REGION':r, 'TECHNOLOGY': t})))
    
m.linexpr(bounds, RTeY) == 0
```
```bash
AnomymousConstraint  (REGION: 1, TECHNOLOGY: 1, YEAR: 4)
--------------------------------------------------------
[SIMPLICITY, TD2, 2010]: 1.0 AccumulatedNewCapacity[SIMPLICITY, TD2, 2010] - 1.0 NewCapacity[SIMPLICITY, TD2, 2010]                                                                                   =  0
[SIMPLICITY, TD2, 2011]: 1.0 AccumulatedNewCapacity[SIMPLICITY, TD2, 2011] - 1.0 NewCapacity[SIMPLICITY, TD2, 2010] - 1.0 NewCapacity[SIMPLICITY, TD2, 2011]                                          =  0
[SIMPLICITY, TD2, 2012]: 1.0 AccumulatedNewCapacity[SIMPLICITY, TD2, 2012] - 1.0 NewCapacity[SIMPLICITY, TD2, 2010] - 1.0 NewCapacity[SIMPLICITY, TD2, 2011] - 1.0 NewCapacity[SIMPLICITY, TD2, 2012] =  0
[SIMPLICITY, TD2, 2013]: 1.0 AccumulatedNewCapacity[SIMPLICITY, TD2, 2013] - 1.0 NewCapacity[SIMPLICITY, TD2, 2011] - 1.0 NewCapacity[SIMPLICITY, TD2, 2012] - 1.0 NewCapacity[SIMPLICITY, TD2, 2013] =  0
```

**Comment by FabianHofmann** [comment]
Hey @willu47, I think you already have chosen a good option. A bit shorter version could be achieved with the `loc` accessor, which is also available on `xarray.DataArray` 's.   


```python 
def bounds(model, r, t, y):
    new_capacity_sum = sum(new_capacity[r,t,yy] for yy in ds.YEAR.values 
                    if (y-yy >= 0) and (y-yy < ds['OperationalLife'].loc[r,t]))
    return accumulated_new_capacity[r,t,y] - new_capacity_sum
```

However, if you like fancy array based implementation, you could also go for this: 

```python 
new_cap = new_capacity.rename(YEAR="BUILDYEAR")
mask = (ds.YEAR - new_cap.data.BUILDYEAR >= 0) & (ds.YEAR - new_cap.data.BUILDYEAR < ds.OperationalLife)
accumulated_new_capacity - new_cap.where(mask).sum("BUILDYEAR") == 0
```

This is both faster and, I think, more transparent. Note that the trick is to rename the `YEAR` dimension in the `new_capacity` variable, i.e. adding one more dimension, and then perform a condition based on a boolean array.  The `mask` function makes a selection on the indexes where the condition holds true. Let me know if that works/helps :)

**Comment by willu47** [comment]
Awesome, thanks a lot.  Yes, that's exactly what I was looking for, and many thanks for the clear explanation!

The bits that were not immediately obvious to me are:
- accessing coordinates via `.` such as `ds.YEAR` rather than `ds.coords['YEAR']`
- use of mask in the `variable.where()` - excellent!
