### ISSUE TITLE
Precision of floats in lp files

### ISSUE THREAD

**Issue by jafluri** [PyPSA/linopy#111]
Hello,

I am currently migrating a package from pyomo to linopy (great work btw). When comparing results from the old version to the results with linopy, I noticed that the results always match pretty well but not exactly, with differences up to around ~1% for complex models. 

I came to realize that the main issue was the precision in which the lp files are written. From what I understand, all of the float to string conversion is happening in

https://github.com/PyPSA/linopy/blob/62ac3ea8f4b3cefef9ca7df55132e6161a8fb699/linopy/io.py#L38-L46

Is there anything against upping the precision per default, e.g. from `%f` -> `%.12f` and `%f` -> `%+.12f` respectively?
If not, it would be great if you could add this. Otherwise, I could create a PR where this is a new parameter that can be passed to the model.

**Comment by FabianHofmann** [comment]
Hey @jafluri, thanks for pointing this out. Correct me, if I am wrong, but the default precision seems to be 6. Since we do not want to bloat the LP size, could you try out whether a precision of 8/9 is already satisfying?

**Comment by jafluri** [comment]
Thanks for the quick reply. I just ran the model for 6, 9, 12 and 15 significant digits. The objective for 9, 12 and 15 is identical. Comparing the variable values to the ones from pyomo, you get the smallest differences with 12 and 15, but I guess 9 should be enough as some floating point jitter is to be expected in large models.

**Comment by jafluri** [comment]
In combination with #112, one could do `"%+.12g"`, that strips away the tailing zeros:

`array([1.       , 1.2      , 1.2334567]) -> array(['+1', '+1.2', '+1.2334567'], dtype=object)`

I'd assume that way you'd safe memory in most cases, even if you go up to 12, compared to the current implementation.

**Comment by FabianHofmann** [comment]
Oh, this sounds great! Could you do a PR?

**Comment by jafluri** [comment]
Thanks for the quick resolution, I'm closing this then.
