### ISSUE TITLE
Relicense to MIT?

### ISSUE THREAD

**Issue by fneum** [PyPSA/linopy#123]
Like we have done for the other packages. It allows broader usage!

**Comment by FabianHofmann** [comment]
Totally agree!

**Comment by pz-max** [comment]
support also from my side :+1:

**Comment by jafluri** [comment]
LGTM, gread idea!

**Comment by robbiemorrison** [comment]
I am not a contributor and don't have a vote.  But if the project does wish to relicense under MIT, then contributer approvals should be **explicit and unambiguous** (and "gread idea" [sic] probably does not class as such).

**Comment by jankaeh** [comment]
👍🏼

**Comment by lumbric** [comment]
I consider my contributions as minor and I agree to any form of relicensing, in particular also to MIT.

**Comment by coroa** [comment]
Sure, i am happy with relicensing linopy under the MIT license.

**Comment by Cellophil** [comment]
Hi, I admire the spirit, sure!
