### ISSUE TITLE
Initialization of optimization problem to reduce calculation time

### ISSUE THREAD

**Issue by TohokuEva** [PyPSA/linopy#135]
Hello,

I would like to initialize my optimization problem to reduce calculation time, but I have not found how to do it.
Any insights about this topic would help me a lot.

Many thanks in advance!
Eva

**Comment by FabianHofmann** [comment]
Hey @TohokuEva! 
Thanks for your question. However, I am not sure what you mean exactly. In case you mean the solving time, I would recommend to look at the solver docs (Highs, Gurobi) and see whether you get some information there. Linopy cannot do much about that. If you mean the linopy model creation and passing to the solver, that is another story. In this regard, I have to update the docs. 
Best wishes

**Comment by FabianHofmann** [comment]
Hey Eva, the VarHintVal seems to be useable for special cases. It seems to me that this feature might be beyond the scope of linopy. 
Let me allow to close the issue, as it remains quite vague. Happy to support, if you have particular questions.
