### ISSUE TITLE
removing variables, index counter and storage_units

### ISSUE THREAD

**Issue by Cellophil** [PyPSA/linopy#143]
Hi,

Linopy version 0.0.14;

We had a bug (we think) which surfaced when we added additional variables to the model. There seemed to be a gap in the index, so our new variables started at an offset. Digging into it we think the reason was a pypsa storage_unit, which initiated variables for spilling; no spilling was used so pypsa tried to remove the variables. (Adding a spilling of 1e-7 or so removes the variable index offset and fixes the bug). So it seems removing variables doesn't reset the variable index correctly; or it's an incorrect call to remove variables within pypsa.

Steps to reproduce:
```
n = pypsa.Network()
n.add('Bus', name='b')
n.add('StorageUnit', name='s', bus='b', marginal_cost=1)
n.optimize.create_model()
n.model.add_variables(coords=[n.buses.index], name='Bus-something')
n.model.variables
```

Spilling lower bound looks weird... New variables have an offset.

**Comment by Cellophil** [comment]
I'll update both packages, that's overdue, and check whether the error still persists.

**Comment by Cellophil** [comment]
Ok I checked, there'll still be variables created for spilling, then removed, which causes a variable offset. Maybe this is intended and not a problem.
How we ran into this: the highs solver instance (highspy) can report it's number of Rows, aka number of variables, which is then lower than the variable indexes of the linopy model. I'm not exactly sure whether the highs solver expect variables without gaps, possibly "number of variables" isn't necessarily equal to "highest variable index".
Reporting this here in linopy since variable removing and keeping track of the index is on linopy side.

**Comment by Cellophil** [comment]
![grafik](https://github.com/PyPSA/linopy/assets/58934815/ea73de66-2f4f-4e63-9c1d-f06ccffcd100)

**Comment by FabianHofmann** [comment]
Hey @Cellophil, that is actually the intended behavior.  The offset comes from the spilling variables which were created but masked out. The effective counter then starts at a later point. However, did you run into any bugs? 

As for the number of variables, you should probably compare `n.model.nvars` / `n.model.ncons` with the number of columns and rows reported by highs.

**Comment by Cellophil** [comment]
Ok I'll check - the highs interface isn't too verbose on what it didn't like about me adding constraints; I thought it's the discrepancy between highs numRows < model.variables.labels, probably that's actually ok.

I checked in the code, it's
`h.addVars(len(M.vlabels), M.lb, M.ub)`
In the example M.vlabels has gaps:
![grafik](https://github.com/PyPSA/linopy/assets/58934815/5a2c3409-d53a-482b-b69f-4b247d70141f)

so highs gets an internal index different from the labels or the linopy model. The gaps are removed on the fly. Labels are reshaped like
`labels = np.arange(len(vtypes))[(vtypes == "B") | (vtypes == "I")]`

The constraint matrix is not reshaped as far as I can see. I'm maybe overlooking something, but that shouldn't work? Maybe it would be better to just create the full amount of variables np.arange(max(M.vlabels)).

Structurally, would it make sense to deduct the offset from all indices when a variable is removed? On the other hand if the solvers don't mind...

**Comment by Cellophil** [comment]
Constraint matrix is also compressing the variables if there's gaps, so the shape runs till 31 in the example. So it matches. So overall my misunderstanding, I thought labels match to the index within the solver. Can be closed.

**Comment by FabianHofmann** [comment]
perfect, thanks for reporting!

**Comment by FabianHofmann** [comment]
FYI: The labels that associated with the columns and rows of the constraint matrix are in `model.matrices.vlabels` / `model.matrices.clabels`

**Comment by Cellophil** [comment]
Understood - they align mostly with the solver indices, but possibly with offset. That's a difference to the early pypsa version, there the index from get_var was literally the index within the solver. That was what I was confused about, but to be fair "label" also implies a more general concept compared to "index".
