### ISSUE TITLE
Implement .fillna for Variables

### ISSUE THREAD

**Issue by hblunck** [PyPSA/linopy#144]
I am running linopy version 0.2.2. I want to `shift` a variable along a dimension and fill the resulting "null" values with a specific value.

I tried:
```python
m = Model()
x = m.add_variables(lower=0, dims="time", coords=[[1,2,3]])
```

When I run `x.shift(time=1)` I get (as expected):

> Variable (time: 3) - 1 masked entries
>[1]: None
>[2]: var1[1] ∈ [0, inf]
>[3]: var1[2] ∈ [0, inf]

However, I cannot fill the NA value using `.fillna`. E.g. `x.shift(time=1).fillna(5)` will result in the same output as above.

**Comment by hblunck** [comment]
So the following appears to work:
```python
x.to_linexpr(1.0).shift(time=1).fillna(value={"const": 10})
```

Why it does is beyond me ;-)

**Comment by FabianHofmann** [comment]
Good point, thanks for raising this. Indeed, the `LinearExpression` is a bit more performant for such cases, but it should work for variables too.

**Comment by FabianHofmann** [comment]
Hey @hblunck, I added a warning if the fillna method receives a non-variable type. This makes the function mush safer I think. However, for expression I added a convenience case that constant values can directly be passed:

```python
x.to_linexpr(1.0).shift(time=1).fillna(10)
```

Feel free to try and report if there is a problem.
