### ISSUE TITLE
add a 'symbolic_solver_labels' option to to_file() 

### ISSUE THREAD

**Issue by ulfmueller** [PyPSA/linopy#169]
Using pyomo I often use the io_options={'symbolic_solver_labels': True} when writing the lp-file, which gives a nice human-readable version of the linear problem. I was wondering if sth. like this would be possible when using linopy and if not so far, if s.th. like that would be a nice feature (I'd like it :wink: )...

**Comment by FabianHofmann** [comment]
Hey @ulfmueller, thanks for your message. The issue was already raised in #157. I am closing this in favor of the other.
