### ISSUE TITLE
CPLEX solving with "integer optimal, tolerance"

### ISSUE THREAD

**Issue by BuiMCanmet** [PyPSA/linopy#176]
Hello,
When using PyPSA, sometimes I will get the following solution message when solving with CPLEX:

```
WARNING:linopy.solvers:Solution status unknown. Trying to parse solution.
WARNING:linopy.solvers:Dual values of MILP couldn't be parsed
WARNING:linopy.constants:Optimization failed: 
Status: unknown
Termination condition: unknown
Solution: 149574 primals, 0 duals
Objective: 8.00e+08
Solver model: available
Solver message: integer optimal, tolerance

Solved Year 2021, UC Period 0 ((2021, Timestamp('2021-01-01 00:00:00')) to (2021, Timestamp('2021-01-18 04:00:00'))). Runtime: 141 seconds
INFO:pypsa.io:Exported network output_2021 has loads, lines, storage_units, buses, links, generators, carriers, line_types

```
The message output integer optimal, tolerance but this status isn't recognized within linopy so the status becomes unknown. For the moment, I am fixing this issue by changing the following dictionary values within the linopy/solvers.py:

Original version (Line 422):
```
    CONDITION_MAP = {"integer optimal solution": "optimal"}

    if io_api is not None and io_api not in ["lp", "mps"]:
        logger.warning(
            f"IO setting '{io_api}' not available for cplex solver. "
            "Falling back to `lp`."
        )

```

Temporary fix:
```
    CONDITION_MAP = {"integer optimal solution": "optimal", "integer optimal, tolerance": "optimal"}
    if io_api is not None and io_api not in ["lp", "mps"]:
        logger.warning(
            f"IO setting '{io_api}' not available for cplex solver. "
            "Falling back to `lp`."
        )
```

Maybe, it is not the best solution but that's what I came up with for the moment. I am not too familiar what's the difference between "integer optimal, tolerance" versus "integer optimal solution" but maybe a better approach can be defined also.

Cheers!

**Comment by FabianHofmann** [comment]
Hey @BuiMCanmet, thanks for raising this. Your approach looks totally reasonable. Would you like to suggest a PR? Otherwise I can do it :)
