### ISSUE TITLE
`linopy.version` not found with `pip install`?

### ISSUE THREAD

**Issue by fneum** [PyPSA/linopy#187]
https://github.com/PyPSA/linopy/blob/c1186a3079450b3827b41203e17edfb27360b56c/linopy/__init__.py#L21

Gives ModuleNotFoundError when installed from PyPI, but not with development version `pip install -e .`

**Comment by FabianHofmann** [comment]
does that mean you cannot import linopy when installed from pypi at all? or is just the call `linopy.__version__`

**Comment by fneum** [comment]
Could not import `linopy` if installed from PyPI

**Comment by FabianHofmann** [comment]
I just tested this and it works fine:

```bash
conda create -n test python==3.11
python -m pip install linopy
python
```

```python
import linopy
linopy.Model()
```

The version is also displayed correctly.

**Comment by fneum** [comment]
Must have been a local error. Your code works for me, too and now I can't reproduce.
