### ISSUE TITLE
How to write 2D constraints while the right side is 1D.

### ISSUE THREAD

**Issue by loongmxbt** [PyPSA/linopy#21]
I have a `df_units` dataframe and a `df_time` dataframe.
```
      is_uc  bus  p_min   p_max  ...  cold_start_cost  no_load_cost  shut_down_cost  cold_start_hours
G01a      1  B01  100.0  1000.0  ...            150.0         100.0           120.0               3.0
G01b      1  B01  100.0  1000.0  ...            150.0         100.0           120.0               3.0
G02       1  B02  100.0  1000.0  ...            150.0         100.0           120.0               3.0
G03       1  B03  100.0  1000.0  ...            150.0         100.0           120.0               3.0
```
 I define a `unit_power` continuous variable 2-D, and a `bx` binary variable 2-D.
```
    bx = m.add_variables(binary=True, coords=[df_time.index, df_units.index], name='bx' )
    unit_power = m.add_variables(lower=0, coords=[df_time.index, df_units.index], name='unit_power' )
```

I want to define constrains, for every time `bx*unit_power` must greater than `p_min` and `unit_power` must less than `p_max`.
But the dimensions are not the same. 

What's the recommended way to write such constraints?  
Do I need to broadcast the right side into matrix? That seems needs an extra amount of memory. 
Or do I need to write within loops?
Thanks!

```
m.add_constraints(bx*unit_power >= df_units_uc['p_min'], name='min_power_constraint')
m.add_constraints(unit_power * 1 <= df_units_uc['p_max'], name='max_power_constraint')
```

**Comment by FabianHofmann** [comment]
Hey @loongmxbt , the broadcasting works automatically in linopy, so no need for loops or extra broadcasting. I am not sure if `df_units_uc.index` is now a subset of `df_units.index`? 
Either way, what you wrote in the last section should work if the dimension names are set correctly(!). What I suggest to you is that you explicitly set the names of your axes in the dataframe before defining the variables and constraints. Something like 

```
df_time.index.name = 'time'
df_units.index.name = 'units'

bx = m.add_variables(binary=True, coords=[df_time.index, df_units.index], name='bx' )
unit_power = m.add_variables(lower=0, coords=[df_time.index, df_units.index], name='unit_power' )

m.add_constraints(bx*unit_power >= df_units['p_min'], name='min_power_constraint')
m.add_constraints(unit_power * 1 <= df_units['p_max'], name='max_power_constraint')
```
(Assuming now, that `df_units` equals to `df_units_uc`)
Hope that helps!

**Comment by joga4er** [comment]
To clarify the imports:

```
import linopy as opt
import numpy as np
import pandas as pd
```

**Comment by joga4er** [comment]
Sorry for spaming this issue:

The solution is to multiply the variable with one:
```
#constraint
m.add_constraints(  content * 1 >= storage_df[ 'Tmin' ], name = 'content_low' )
```

**Comment by FabianHofmann** [comment]
Good that you found a solution. I will update the docs soon on how to work with pandas objects and different approaches to create constraints. But note, always watch out for the names of the dimensions (that the most "tricky" thing)
