### ISSUE TITLE
Cannot import "Coordinates" from xarray

### ISSUE THREAD

**Issue by erik-rossbach-DUS** [PyPSA/linopy#216]
In the file **expressions.py**, line 23, there is a call to import **Coordinates** from xarray

However, this line kept raising an error:

*ImportError: cannot import name 'Coordinates' from 'xarray'*

I have found simply removing the `s` in 'Coordinates' fixed this issue:

`from xarray import Coordinate**s**, DataArray, Dataset` -> `from xarray import Coordinate, DataArray, Dataset`

**Comment by FabianHofmann** [comment]
interesting, could you say which xarray version you are using?

**Comment by erik-rossbach-DUS** [comment]
I am using:
* xarray v. 2023.1.0
* linopy v. 0.3.2

**Comment by FabianHofmann** [comment]
could you update your xarray version and try again?

**Comment by erik-rossbach-DUS** [comment]
I was under the wrong impression that I had the most recent version of xarray installed.

Indeed, the import statement works with the most recent release of xarray v. 2023.12

Thank you for your help!
