### ISSUE TITLE
[Feature] Support early stopping for solving such as allowing a relative optimality gap

### ISSUE THREAD

**Issue by Martin-Jung** [PyPSA/linopy#221]
In many use cases it might not (computationally) be desirable to solve a (M)IP to a optimal solution, particular so for problem formulations with large number of constraints where it can occur quite often that the solver tries for hours to search for an optimal solution.

Most commercial and open-source solvers support early stopping criteria, for example [MIPGap](https://support.gurobi.com/hc/en-us/articles/8265539575953-What-is-the-MIPGap) and [timelimit](https://www.gurobi.com/documentation/current/refman/timelimit.html) parameters for Gurobi.

Would it be possible to support something like this within `linopy`, maybe as parameter for solve?

**Comment by FabianHofmann** [comment]
Hey @Martin-Jung, passing parameters to solvers is supported but via the `solve` function, but have to be in line with the individual solver parameters. For example, for gurobi the time limit can be passed via

```python 
m.solve(solver_name="gurobi", TimeLimit=200)
```

I would close this issue. But if things remain unclear, please reopen :)
