### ISSUE TITLE
Docs errata: LinearExpression `expand_dims`

### ISSUE THREAD

**Issue by Lkruitwagen** [PyPSA/linopy#288]
FYI `LinearExpression.expand_dims` not currently supported, but is written up in the [docs](https://linopy.readthedocs.io/en/latest/generated/linopy.expressions.LinearExpression.html). 

Found a work-around using `assign_coords` to expand out my desired dimension. Might be a quick PR to support? Will take a look.

**Comment by FabianHofmann** [comment]
hey @Lkruitwagen, thanks for your message. The function is already there, are you on the latest version or the current master branch?

**Comment by Lkruitwagen** [comment]
ah - nice one! Congrats on the release :)
