### ISSUE TITLE
How are "0" coefficient passed to gurobi?

### ISSUE THREAD

**Issue by KanaBaradei** [PyPSA/linopy#293]
Hi to everyone!
I have a model that has some calculations that yield some variables to be multiplied by 0, like this:
`0*y(1,2)+22*y(1,3)+....>=1000`
The values are chosen at random for this example.
I want to make sure that sending that to gurobi does not create problems, my ideal behavior would be that the expression is treated as this:
`22*y(1,3)+....>=1000`
Ergo, to just omit the ones that have 0s.
Does it work similar to this? Does anyone know if it's not a problem?
Thanks in advance!

**Comment by FabianHofmann** [comment]
Hey @KanaBaradei, zeros are dropped in the export to the solvers :) hope that solves your issue. Reopen if there is anything left.

**Comment by FabianHofmann** [comment]
Yes, that should be fine, but have a look at the resulting objective to make sure the expressions are added correctly.
