### ISSUE TITLE
masking vs selecting

### ISSUE THREAD

**Issue by aurelije** [PyPSA/linopy#307]
Hi linopyers, I am wondering if I am using linopy correctly while creating constraints.

In many occasions I have to setup constraint that applies only to a subset of one dimension. For example there is a time dimension but constraint applies only to some dates. In that case I see 2 ways of constructing constraint:

1. select variables/linear expression by time dimension getting only those on which you would construct constraint. This approach is usually more explicit, simpler to understand and creates dense constraint
2. use masking in add_constraints, constraint is sparse because all constraint coordinates will be printed with masked out displayed as None

Are both approaches equally good? What are the pros and cons?

**Comment by FabianHofmann** [comment]
Hey, I would say that both approaches work equally good. The selection might be a bit cleaner and a bit more memory efficient, as no placeholders are required.

**Comment by aurelije** [comment]
Thanks @FabianHofmann for confirming my taught

**Comment by FabianHofmann** [comment]
sure :) closing this
