### ISSUE TITLE
0.3.12 ModuleNotFoundError: No module named 'highspy'

### ISSUE THREAD

**Issue by michalmarszal** [PyPSA/linopy#320]
@FabianHofmann 
0.3.12 released on pypi.org forces to have highspy installed, without having it added to dependency in pyproject.toml. I do not see point of installing HiGHS when I am using the other solver.
This is cased by small import in linopy/io.py:20 which is used just for typing hint
See PR to fix the issue:
https://github.com/PyPSA/linopy/pull/319

**Comment by FabianHofmann** [comment]
Hey @michalmarszal, highspy is a dependancy as it is used for writing mps files to disk

**Comment by michalmarszal** [comment]
But it is not listed as a "vanilla" dependency in pyproject.toml !!!!
https://github.com/PyPSA/linopy/blob/f25f208daaff1ef5f5aae916f937eca4df0685fa/pyproject.toml#L22
It is listed as optional dependency.

Hence when i'm importing linopy in other projects using dependency pyproject.toml i got Module Not Found Error.
Ergo i am not able to use linopy without HIGHS!

**Comment by FabianHofmann** [comment]
gotcha, thanks for raising
