### ISSUE TITLE
Overhaul CI and CD workflows

### ISSUE THREAD

**Issue by afuetterer** [PyPSA/linopy#325]
As previously discussed here: https://github.com/PyPSA/linopy/issues/313#issuecomment-2213371885.

I would like to propose the following changes. These might be used in the other PyPSA repos as well, if desired.

- Have a CI workflow, including pytest etc, and one run of "baipp", running on PR and push to master
- Have a CD workflow, running on tag, creates a GH release, publishes to PyPI and what else is desired.

Proposal to follow these guidelines:
https://learn.scientific-python.org/development/guides/gha-pure/
As used in their template:
https://github.com/scientific-python/cookie/tree/main/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows

What do you think?

**Comment by FabianHofmann** [comment]
Great initiative @afuetterer! I think that sounds good, let's hear what @lkstrp thinks :)

**Comment by lkstrp** [comment]
Structurally there is no big difference to what is currently done in PyPSA, is there? 
But building wheels instead and adding artifacts looks great, so let's go!

**Comment by afuetterer** [comment]
No, not really that big of a difference. But having ci and cd in all your repos males it much more readable, I think.
Sometimes you have "tests", "release", "deploy".

I will make a suggestion then?

**Comment by afuetterer** [comment]
Your cd workflows start by pushing a tag, right?

**Comment by FabianHofmann** [comment]
exactly

**Comment by lkstrp** [comment]
> Your cd workflows start by pushing a tag, right?

Yes. Right now it's basically: tests -> CI, deploy -> CD. Except in linopy, there is also release, which should be moved in deploy/ CD.

In some repos there will be a validation CI soon. I think it is better to keep that workflow seperated from the Tests CI. Even if it could lead to some redundancy with the build job. So let's in my view, let's stick with tests.yml and deploy.yml (and in future validate.yml) everywhere.
