### ISSUE TITLE
Support MIP

### ISSUE THREAD

**Issue by aurelije** [PyPSA/linopy#33]
As I can see in the docs and code there is no support for integer programming, only continuous and binary variables are supported. Is there a plan to get integer variables soon?

Thanks for great project

**Comment by FabianHofmann** [comment]
Hey @aurelije, indeed these are not supported right now, though it would be easy to introduce them. I'll keep you updated when I tackle this (probably in the next months) except you want to create a PR, then I could guide you a little.
