### ISSUE TITLE
Do you, good developer, want these notebook tutorial examples in the linopy repo?

### ISSUE THREAD

**Issue by tpu-brunkhorst** [PyPSA/linopy#348]
Hi - I wrote a couple of linopy example notebooks on my github page [here](https://github.com/tpu-brunkhorst/TP_datascience_public/tree/main/linopy_examples)

One is a monthly energy portfolio model and the other is a sudoku puzzle solver :)

Let me know if you want one or both of these and I can try to step through the PR process.

-Greg

**Comment by FabianHofmann** [comment]
Wow, lovely!  Yes please, they look really nice!
