### ISSUE TITLE
Solver module import other errors

### ISSUE THREAD

**Issue by loongmxbt** [PyPSA/linopy#38]
In solvers.py
```
try:
    import gurobipy

    available_solvers.append("gurobi")
except ModuleNotFoundError:
    pass


try:
    import cplex

    available_solvers.append("cplex")
except ModuleNotFoundError:
    pass

try:
    import xpress

    available_solvers.append("xpress")
except ModuleNotFoundError:
    pass
```

When we have other solver installation errors besides ModuleNotFoundError, it will stuck.

E.g. I have a legacy cplex installation, and I want to use highs, it will always stuck in the step importing cplex.

**Comment by FabianHofmann** [comment]
Thanks for the report @loongmxbt, what kind of error is raised in this case? Perhaps we can extend the list of exceptions here.

**Comment by FabianHofmann** [comment]
Could you check it out with the current master?

**Comment by loongmxbt** [comment]
@FabianHofmann Thanks, now both envs work fine.
