### ISSUE TITLE
Nice printout of new constraints

### ISSUE THREAD

**Issue by fneum** [PyPSA/linopy#6]

**Comment by loongmxbt** [comment]
Hi, when I use `model.to_file('./model.lp')`, the `lp` file does not contain the "variable name" and "constraint name" which I set in python file. All vars in .lp file is named `x{number}`. Which makes it hard to find model problem. 
I'm new to xarray and I need to check if I write things right.
So is this an intended feature and how to print `.lp` files with var and constraint names?

**Comment by FabianHofmann** [comment]
Hey @loongmxbt, the lp file is not the optimal place to inspect the model as is it reduced to the pure mathematical problem without any further information. But if you still want to do it, you can use the functions `model.variable.get_name_by_label` where you can insert the variable label (the number after `x`) and get the corresponding variable name.
